# Generated by Django 3.1.6 on 2022-08-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Наименование банка')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('term_min', models.IntegerField(default=0, verbose_name='Срок ипотеки, ОТ')),
                ('term_max', models.IntegerField(default=0, verbose_name='Срок ипотеки, ДО')),
                ('rate_min', models.FloatField(default=0, verbose_name='Ставка, ОТ')),
                ('rate_max', models.FloatField(default=0, verbose_name='Ставка, ДО')),
                ('payment_min', models.IntegerField(default=0, verbose_name='Сумма кредита, ОТ')),
                ('payment_max', models.IntegerField(default=0, verbose_name='Сумма кредита, ДО')),
                ('bank_name', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='calc.bank',
                    to_field='name',
                    verbose_name='Наименование банка')),
            ],
        ),
    ]
